name: slack-notify

on:
  push:
    branches: [ blockkit-support ]
  pull_request:

jobs:
  build-slack-notify:
    runs-on: ubuntu-latest

    outputs:
      digest: ${{ steps.docker_build.outputs.digest }}

    permissions:
      contents: read
      packages: write
      pull-requests: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Golang
      uses: actions/setup-go@v3
      with:
        go-version: '1.20.1'
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Build
      run: |
        mkdir -p bin/
        GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o bin/slack-notify ./main.go
    
    - name: Log in to the GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/tf-dive/slack-notify
        tags: |
          type=raw,value=dev
          type=semver,pattern={{ version }}

    - name: Build image and publish to registry
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        file: ./Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          GIT_REV=${{ github.sha }}
